### ISSUE TITLE
homebrew

### ISSUE THREAD

**Issue by drewsonne** [ewilde/terraform-provider-runscope#1]
Hi!

I'm about to start using your provider. I've created a homebrew formula for using your provider locally local work, and thought you may be interested given the recent changes to how terraform deals with 3rd party providers (ie, they don't).

You can see it here.

https://github.com/drewsonne/homebrew-tap/blob/master/terraform-provider-runscope.rb

**Comment by ewilde** [comment]
Hi Drew,

Thanks for that, I'm hoping to get this provider added as an official community provider sometime in the near future. In the meantime this looks very handy.

**Comment by ewilde** [comment]
[0.10.x](https://github.com/ewilde/terraform-provider-runscope/tree/0.10.x) branch now created and I've started to [review process](https://www.terraform.io/guides/terraform-provider-development-program.html) to get the provider added

**Comment by drewsonne** [comment]
Hi @ewilde any luck on this?

**Comment by ewilde** [comment]
@drewsonne not really, I got some feedback a couple of weeks ago 

>  there hasn't been much movement in the release of new providers but we would like to make your provider visible to the Terraform community before the provider is officially verified and tested by HashiCorp, we would like to list your provider on our Terraform Community Providers page.

I've filled out that form and it's now visible on the [community page](https://www.terraform.io/docs/providers/type/community-index.html)

I've asked if the provider is still being reviewed or in a queue to be reviewed and will keep this issue updated when I get more information.

**Comment by ewilde** [comment]
@drewsonne just heard back from hashicorp and the runscope provider is still in their queue to be reviewed for inclusion as an official plugin

**Comment by ewilde** [comment]
closed by #27
