### ISSUE TITLE
Runscope - Retry on Failure

### ISSUE THREAD

**Issue by labithiotis** [ewilde/terraform-provider-runscope#13]
Hi could you please support `retry-on-failure` under behaviours.
[https://www.runscope.com/docs/api-testing/behaviors#retry-on-failure](https://www.runscope.com/docs/api-testing/behaviors#retry-on-failure)

**Comment by philwhiteuk** [comment]
@labithiotis should do the trick https://github.com/ewilde/terraform-provider-runscope/pull/17

**Comment by ewilde** [comment]
closed by #17
