### ISSUE TITLE
add support for regions on environment

### ISSUE THREAD

**Issue by cristianrgreco** [ewilde/terraform-provider-runscope#2]
We would like to be able to configure regions when deploying an environment, but this is not implemented currently:

https://www.runscope.com/docs/api/environments#list

**Comment by ewilde** [comment]
@cristianrgreco no problem i'll add this

**Comment by ewilde** [comment]
@cristianrgreco I've [commited the change](https://github.com/ewilde/terraform-provider-runscope/commit/354c439178ce6a8ee330d08b61a1bb487cfef1c8) and its in the new release https://github.com/ewilde/terraform-provider-runscope/releases/tag/v0.2.0
