### ISSUE TITLE
integrations documentation is incorrect

### ISSUE THREAD

**Issue by calebcase** [ewilde/terraform-provider-runscope#22]
The integrations documentation indicates it is a list of objects, but it is now required to be a list of ids.

```
  integrations = [
    {
      id               = "${data.runscope_integration.pagerduty.id}"
      integration_type = "pagerduty"
    }
  ]
```

This needs to be changed to:

```
  integrations = [
      "${data.runscope_integration.pagerduty.id}",
  ]
```

https://github.com/ewilde/terraform-provider-runscope/blob/master/website/source/docs/providers/runscope/r/environment.html.markdown

**Comment by ewilde** [comment]
@calebcase thanks for raising this issue, now fixed.
