### ISSUE TITLE
Wrong version reported by terraform 0.0.0

### ISSUE THREAD

**Issue by Mistobaan** [ewilde/terraform-provider-runscope#23]
Seems something has changed in terraform's version spec:

> The naming scheme for provider plugins is `terraform-provider-NAME_vX.Y.Z`, and Terraform uses the name to understand the name and version of a particular provider binary. Third-party plugins will often be distributed with an appropriate filename already set in the distribution archive so that it can be extracted directly into the plugin directory described above.

from: https://www.terraform.io/docs/configuration/providers.html

this happens also in other plugins see https://github.com/zambien/terraform-provider-apigee/issues/9

**Comment by ewilde** [comment]
@Mistobaan thanks for raising that. The latest release fixes this problem

**Comment by Mistobaan** [comment]
@ewilde can you double check?
```
2018/02/09 05:34:52 [WARN] found legacy provider "terraform-provider-runscope-v0.5.3"
2018/02/09 05:34:52 [DEBUG] found valid plugin: "runscope-v0.5.3", "0.0.0", "/home/jenkins/.terraform.d/plugins/linux_amd64/terraform-provider-runscope-v0.5.3"
```
