### ISSUE TITLE
Initial Provider Review

### ISSUE THREAD

**Issue by paultyng** [ewilde/terraform-provider-runscope#27]
Hello! 

My name is Paul, I'm a member of the Terraform team @ HashiCorp.

I’ve taken a look at the provider here and would like to say it looks great! I am a past Runscope user, and this would have definitely helped me a lot in my previous roles. I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issue as a sort of checklist for tracking remaining items and discussion. The review was done on the git commit 46326fc36b9313701069d68cbc94f5edec8c3944.

* [x] You may want to run [`golint`](https://github.com/golang/lint) against this (most editors can automatically). We don't currently have a linting standard (maybe coming soon), but I'm sure it will be part of it, some of your naming does not meet the standard Go style, this is not a required change for unexported code yet.
* [x] Can use [`schema.EnvDefaultFunc`](https://github.com/terraform-providers/terraform-provider-aws/blob/a28d44b774cb857974a16cd886beef1f1a73e8a9/vendor/github.com/hashicorp/terraform/helper/schema/schema.go#L216-L224) (you do not need to worry about the `true`/`false` issue I don't believe), instead of reimplementing: https://github.com/ewilde/terraform-provider-runscope/blob/46326fc36b9313701069d68cbc94f5edec8c3944/runscope/provider.go#L46-L58 
* [x] We typically order our imports with stdlib ones first, then whitespace, then the rest (`goimports` can help with this):

Instead of:
```golang
import (
	"fmt"
	"github.com/ewilde/go-runscope"
	"github.com/hashicorp/terraform/helper/schema"
	"log"
	"strings"
)
```
We would do:
```golang
import (
	"fmt"
  "log"
	"strings"
  
	"github.com/ewilde/go-runscope"
	"github.com/hashicorp/terraform/helper/schema"
)
```
* [x] Does this also need to handle a `404`: https://github.com/ewilde/terraform-provider-runscope/blob/46326fc36b9313701069d68cbc94f5edec8c3944/runscope/resource_runscope_bucket.go#L64
* [x] `TypeList` should only be used for ordered lists, otherwise you should use a [`TypeSet`](https://www.terraform.io/docs/extend/schemas/schema-types.html#typeset). The reason is that ordering changes can result in spurious diffs. You maybe using the appropriate things, but just making it clear as I would assume some of these aren't ordered, like: https://github.com/ewilde/terraform-provider-runscope/blob/46326fc36b9313701069d68cbc94f5edec8c3944/runscope/resource_runscope_environment.go#L60
* [x] You probably don't need to export the `Config` struct and `Client` methods: https://github.com/ewilde/terraform-provider-runscope/blob/46326fc36b9313701069d68cbc94f5edec8c3944/runscope/config.go#L14
* [x] `validateValueFunc` is unused
* [x] The error checking in this test is a little weird, the error is checked kinda late, and the error from `Unmarshal` is not captured: https://github.com/ewilde/terraform-provider-runscope/blob/46326fc36b9313701069d68cbc94f5edec8c3944/runscope/resource_runscope_step_token_test.go#L75-L81
* [x] Missing docs for `runscope_integrations` data source, `runscope_step_token` resource.
* [x] Need to rename the file for the `runscope_test` resource and remove the `item` suffix.

Overall this provider is great and I'm looking forward to merging it in to the terraform-providers org!

Thanks,
Paul

**Comment by ewilde** [comment]
Hi @paultyng thank you so much for raising this issue, very excited to work on this and become a member of the terraform-providers family. I'll update your task list above as I make progress

**Comment by ewilde** [comment]
@paultyng think i'm go to go with these changes in PR #28 . Only thing I wanted to check with you was:

> Need to rename the file for the runscope_test resource and remove the item suffix.

When I do that it seems the main runscope package won't import that contents of that file, so provider.go can't find the function `resourceRunscopeTest` i'm guessing this is because the file ends in `_test.go` now, which was why I originally added the `_item.go` suffix. Not sure if there is a work around here? For now I added an `_` suffix, but that seems hacky. Any advise?

**Comment by ewilde** [comment]
@paultyng ready for your feeback, thanks!

**Comment by paultyng** [comment]
Regarding the suffix issue, makes sense, sorry I didn't catch that. There may be a workaround with build tags but probably hackier than necessary, so really your call on this one, you can go back to the previous name, I would just include a comment inside the file about the naming maybe?
