### ISSUE TITLE
unable to add remote agents to environment

### ISSUE THREAD

**Issue by philwhiteuk** [ewilde/terraform-provider-runscope#6]
We would like to add `remote_agents` to environments but this is not currently implemented.

As per https://www.runscope.com/docs/api/agents

**Comment by philwhiteuk** [comment]
@ewilde I created a pr for this here https://github.com/ewilde/terraform-provider-runscope/pull/5 

I have compiled locally and tested and works for me! 🏆

**Comment by ewilde** [comment]
closed by #5
