### ISSUE TITLE
Test Step Concurrency 

### ISSUE THREAD

**Issue by kushmansingh** [ewilde/terraform-provider-runscope#8]
So I noticed that the IDs for the test steps aren't being set properly. I've traced this down to here https://github.com/ewilde/go-runscope/blob/1c4acc6628957c6402f929cdff2f2894ba207ef7/test_step.go#L26 . What happens is that terraform will try to create multiple test steps concurrently. 

So the heuristic of grabbing the 'last created' step from the response fails if something else was also created at the same time. I'm not sure how to proceed from here but I can create a PR with a test case that at minimum replicates the problem

**Comment by kushmansingh** [comment]
Actually this is a bug on Runscope's end. If you do two simultaneous POSTs to create steps, they both get the response with both steps in them. I've opened a support ticket with them.

**Comment by ewilde** [comment]
@kushmansingh thanks for logging this issue, are you able to reproduce this in a PR? I would be interested to see the problem as it arises in terraform

**Comment by kushmansingh** [comment]
If you just add another test step to resource_runscope_step_test.go, your tests will start failing. The behavior you see in Terraform is that the steps have the wrong ID saved to their state, which leads to them being recreated/modified over and over.

This gist may help clarify the issue https://gist.github.com/kushmansingh/fde6930494a9566e3a374e3e4d011367

**Comment by kushmansingh** [comment]
I got this response from Runscope

>Our engineering team has looked at this. We don't make any guarantees about parallel POSTs to adding steps to the same test being an atomic operation. If you want to guarantees a particular behavior then you should make sequential POSTs.


So unless there's some way for Terraform to sequentially create test steps, this is a no-go.

**Comment by ewilde** [comment]
@kushmansingh think this commit solves this problem: https://github.com/ewilde/terraform-provider-runscope/commit/adc1412fb4f1df54fd30a4984bc316a0edacae36

I added a new test with multiple steps, which now passes

**Comment by kushmansingh** [comment]
Looks great. It's unfortunate that the Runscope API negates parallelism but it is what it is. Thanks for the attention!

**Comment by ewilde** [comment]
yeah agreed it's a weird api!

**Comment by calebcase** [comment]
Thanks @ewilde!
